context-menu: Improve giant context menus / context menus towards the bottom of the page.
mozsearch/mozsearch pull request #471
Opened 2021-12-15 20:40 UTC by emilio

This patch prevents context menus from overflowing the viewport by
making them scrollable, and also positioning them towards the top if you
click down enough the page.

This could be improved in the future, but seems like a trivial
improvement to me.

2021-12-15 20:42 UTC, asutherland commented
xref https://bugzilla.mozilla.org/show_bug.cgi?id=1727557

2021-12-15 20:56 UTC, asutherland requested changes
This seems like a major regression for people's muscle memory by doing this on the bottom 5th of the viewport as the mouse now has to be moved a non-trivial distance to reach the top menu item that is only a pixel away when you're on the top 80% of the viewport.  It seems reasonable if it's only when we're at the bottom of the actual document itself and there's nowhere for the user to scroll, though as noted in https://bugzilla.mozilla.org/show_bug.cgi?id=1727557 I think we could probably just add padding to the bottom of the document to help improve that situation too.

2021-12-30 12:36 UTC, emilio commented
@asutherland I implemented the flipping as discussed, can you take a look? Thanks! :)

2021-12-30 17:27 UTC, asutherland approved these changes
I'm **flipping** out over how great these changes are! ;)

I put this on dev.searchfox.org and this works great.  I also very much appreciate the elegant logic about when to constrain versus flip!  Thank you!

2021-12-30 17:58 UTC, merged